# Project information
site_name: Flama
site_description: "API power up for Flama"
site_author: "José Antonio Perdiguero López"
site_url: "https://flama.perdy.io/"

# Copyright
copyright: "GNU General Public License v3.0; 2018 - Present; José Antonio Perdiguero López"

# Repository
repo_name: "perdy/flama"
repo_url: "https://github.com/perdy/flama"
edit_uri: ""

nav:
    - Home: index.md

# Theme configuration
theme:
    name: material
    palette:
        primary: "deep orange"
        accent: "blue"
    font:
        text: "Fira Sans"
        code: "Fira Mono"
    logo: "images/icon.png"
    favicon: "images/favicon.png"

# Customization
extra:
  social:
    - type: "github"
      link: "https://github.com/perdy"
    - type: "linkedin"
      link: "https://linkedin.com/in/perdy"

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - meta
  - footnotes
  - codehilite:
      guess_lang: false